### ISSUE TITLE
`<%= t(:help) %>` outputs entire content of a .yml translation file as a Hash

### ISSUE THREAD

**Issue by john-999** [svenfuchs/rails-i18n#1092]
`<%= t(:help) %>` will not output the expected translation ...

```
en:
  help: Help
```

... from file `config/locales/defaults/en.yml`

Instead, it will output the content of file `config/locales/views/help/en.yml` ...

```
en:
  help:
    index:
      title: Help
      paragraph_1: Text of paragraph one.
      paragraph_2: Text of paragraph two.
      paragraph_3: Text of paragraph three.
```

... as a `Hash` including everything "below" the key `help:`, i.e.:

`
{:index=>{:title=>"Help", :paragraph_1=>"Text of paragraph one.", :paragraph_2=>"Text of paragraph two.", :paragraph_3=>"Text of paragraph three.", ` ...

Environment used:

- Rails 7.0.4.3
- ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
