### ISSUE TITLE
Defining translations for nested forms in namespaced resources

### ISSUE THREAD

**Issue by cestbalez** [svenfuchs/rails-i18n#1123]
I have the below setup

```ruby
class BudgetLine < ApplicationRecord
  has_many :budget_line_items
  accepts_nested_attributes_for :budget_line_items
end

class BudgetLine::Accommodation < BudgetLine
end

class BudgetLineItem < ApplicationRecord
  belongs_to :budget_line
end
```

Now I'm trying to specify labels for the nested form of `BudgetLineItem` inside `BudgetLine::Accommodation`. According to the i18n [documentation](https://edgeguides.rubyonrails.org/i18n.html#translations-for-active-record-models), you can normally do something like this:

```yml
en:
  activerecord:
    attributes:
      user/role:
        admin: "Admin"
        contributor: "Contributor"
```

This works if the model in question is not namespaced, as with User above. However, when you want to specify a namespaced model it has the same syntax with '/', so it becomes:

```yml
en:
  activerecord:
    attributes:
      budget_line/accommodation/budget_line_items:
        unit: Room
```

which does not work.

I've tried different variations of this, e.g.

```yml
en:
  activerecord:
    attributes:
      budget_line:
        accommodation/budget_line_items:
          unit: Room
```

which also does not work, because this way of specifying namespaces in locales seems to be deprecated..?

As far as I understand, if the label is to be translated correctly in my case, the following should return the correct translation: `BudgetLine::Accommodation.human_attribute_name("budget_line_items.unit")`, but so far I've been unsuccessful in my attempts to target this.

I'm not sure if this is a limitation with the library, of if there's something I'm missing here..?
