### ISSUE TITLE
Normalize tool with inconsistent results?

### ISSUE THREAD

**Issue by pama** [svenfuchs/rails-i18n#1134]
Our normalize tool is supposed to remove double quotes from YAML values, but it's not behaving consistently. In some cases, double quotes get swapped for single quotes. For instance:

``` yaml
activerecord:
  errors:
    messages:
      record_invalid: "Validation failed: %{errors}"
      restrict_dependent_destroy:
        has_one: "Cannot delete record because a dependent %{record} exists"
        has_many: "Cannot delete record because dependent %{record} exist"
```

gets normalized to:

``` yaml
activerecord:
  errors:
    messages:
      record_invalid: 'Validation failed: %{errors}'
      restrict_dependent_destroy:
        has_one: Cannot delete record because a dependent %{record} exists
        has_many: Cannot delete record because dependent %{record} exist
```

`record_invalid` ends up with single quotes instead of double quotes, and `has_many` loses the quotes entirely.

I personally think we should not remove the double quotes to keep our translations similar to the locale files from the Rails project.
