### ISSUE TITLE
activerecord.errors.template.header is ignored (Validation error message header not translated)

### ISSUE THREAD

**Issue by alexeymuranov** [svenfuchs/rails-i18n#118]
Here are the steps to reproduce the problem:

```
$ rails new test_localisation
$ cd test_localisation/
$ rails generate scaffold User name:string
$ rake db:migrate
```

Edit `user.rb`:

```
class User < ActiveRecord::Base
  validates_presence_of :name
end
```

Edit `en.yml` (copy and paste from `https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en-US.yml`):

```
en:
  errors:
    format: "%{attribute} %{message}"

    messages: &errors_messages
      blank: "can't be blank"

  activerecord:
    errors:
      template:
        header:
          one:    "1error prohibited this %{model} from being saved"
          other:  "%{count} errors prohibited this %{model} from being saved"
        body: "There were problems with the following fields:"

      messages:
        record_invalid: "Validation failed: %{errors}"
        <<: *errors_messages

      full_messages:
        format: "%{attribute} %{message}"
```

Start the server:

```
$ rails s
```

Go to `http://localhost:3000/users/new` and submit the empty form.
Do the same after changing `activerecord.errors.template.header` translation.
There is no effect, the translation is not used in rendering the header of the error messages.
(However, `.messages.blank` translation is used.)

I observed this problem when my French localization did not translate the header of the error messages.

Thank you.

Alexey.
