### ISSUE TITLE
Currency data should not be language-specific

### ISSUE THREAD

**Issue by camertron** [svenfuchs/rails-i18n#300]
I'm really more curious than anything: why does Rails (and rails-i18n) tie currencies and locales together?  For example, there doesn't seem to be a way to format currencies in Euros if my locale is set to English-US.  Here's the corresponding data from en.yml:

```
number:
  currency:
    format:
      delimiter: ! ','
      format: ! '%u%n'
      precision: 2
      separator: .
      significant: false
      strip_insignificant_zeros: false
      unit: $
```

The unit is explicitly fixed at "$".  This is especially problematic for countries that speak multiple languages or use multiple currencies (think European Union).
