### ISSUE TITLE
Exclamation marks in YAML

### ISSUE THREAD

**Issue by andyw8** [svenfuchs/rails-i18n#334]
Apologies for posting a question rather than an actual issue, but what do the exclamation marks in the YAML signify? e.g.
```
formats:
      default: ! '%d-%m-%Y'
      long: ! '%B %d, %Y'
      short: ! '%d %b'
```
I've seen [this StackOverflow post](http://stackoverflow.com/questions/11365272/what-do-the-exclamation-marks-in-rails-i18n-translation-yml-file-mean) but it doesn't really make it clear.
