### ISSUE TITLE
Japanese and Korean translations differ

### ISSUE THREAD

**Issue by DaniG2k** [svenfuchs/rails-i18n#374]
I noticed that in the Korean and Japanese locales:

```
detetime:
  distance_in_words:
    less_than_x_minutes:
      other: ! '%{count}분 이하'
```

and

```
detetime:
  distance_in_words:
    less_than_x_minutes:
      other: ! '%{count}分以内'
```

the meanings differ. In Korean it says less than x minutes. In Japanese it says within x minutes. I believe this makes these two localizations inconsistent. Either the Japanese should read `'%{count}分以下'` or the Korean should read `'%{count}분 이내'` for consistency.

Cheers

EDIT: This goes for all the translations where it says 以内 in Japanese and 이하 in Korean.
