### ISSUE TITLE
Error format whitespace in zh-CN

### ISSUE THREAD

**Issue by bastengao** [svenfuchs/rails-i18n#385]
Hi, my english is not good. I see error format in zh-CN.yml is `%{attribute} %{message}`.

``` yml
zh-CN:
  errors: &errors
    format: ! '%{attribute} %{message}'
```

There is a whitespace between `attribute` and `message`.If it is used for English like language, that's ok. But there are no whitespaces between words in sentence in Chinese language. For example,`Email can't be blank` is right in English, `邮箱不能为空字符` is right in Chinese, but `邮箱  不能空字符`.
