### ISSUE TITLE
de-capitalization problem

### ISSUE THREAD

**Issue by pdietrich** [svenfuchs/rails-i18n#4]
Hi!

I have the following problem with I18n and the "label" form helper:

in my de.yml I have:

```
de:
  activerecord:
    attributes:
      feedback:
        email: 'E-Mail-Adresse'
```

In my form I have

```
<% form_for(@feedback) do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %>
<% end %>
```

What happens is that the label method de-capitalizes the string returned by I18n so I get  'E-mail-adresse' in the output which unfortunately is wrong in German.
It is easy to work around this by manually creating an html label tag with a <%= I18n.t 'activerecord.attributes.feedback.email' %> inside.

I think the label form helper should not touch the string returned by I18n.

Cheers,
Patrick

PS: my Rails version is 2.3.4
