### ISSUE TITLE
Display native language name for all locales

### ISSUE THREAD

**Issue by ayswarya** [svenfuchs/rails-i18n#458]
Currently, there is no key that defines the language's native name
Eg: "nihongo" for japanese. Would be good to have one.

**Comment by fjaeger** [comment]
Yes, that would be very helpful!

**Comment by nickstanish** [comment]
@svenfuchs would you be open to a pull request that starts a translation scheme with translations for each locale code?

For example:
```yml
en:
  language:
    en: English
    es: Spanish
    de: German
es:
  language:
    en: Inglés
    es: Español
    de: Alemán
de:
  language:
    en: Englisch
    es: Spanisch
    de: Deutsche
```

Sorry if these are incorrect, I used Google translate for the example
