### ISSUE TITLE
Some locales not rendering

### ISSUE THREAD

**Issue by Zealotux** [svenfuchs/rails-i18n#489]
Hi,

I'm currently using i18n on my application and I don't have any problem with most of it. But some of my pages that used to work well are now suddently not working anymore, I just have the "translation missing" error. The weird thing is: I just have to change the name of the locale to make it work again.

For example I have:

```
   en:
    pro_services:
      index:
        register: "Register"
```

Which will be called in my page by:
```
   = t('.register')
```

On my page, it'll display:

>en, pro_services.index.register

But as soon as I change it to:

```
   en:
    pro_services:
      index:
        registerblabla: "Register"
```
And change it in my HAML file as this:

```
   = t('.registerblabla')
```

It'll work again and display "Register" as planned, this issue is totally random (the page used to render well before), I have two pages that are similar and one of them is working while the other isn't.

Am I missing something? Thanks in advance.
