### ISSUE TITLE
Locales completeness

### ISSUE THREAD

**Issue by korun** [svenfuchs/rails-i18n#495]
Hello!
Quote from `README.md`:

> Currently, no locales are complete. Typically they lack the following keys:
> - `activerecord.errors.messages.record_invalid`
> - `activerecord.errors.messages.restrict_dependent_destroy`

Can we just use:

``` yaml
  errors:
    format: ...
    messages: &errors_messages
      accepted: ...
      ...
  activemodel:
    errors:
      messages:
        <<: *errors_messages
  activerecord:
    errors:
      messages:
        <<: *errors_messages
```

If it so, I can make PR for all locales.
