### ISSUE TITLE
Showing all the subtree of translations

### ISSUE THREAD

**Issue by Startouf** [svenfuchs/rails-i18n#522]
Let's say I have the following tree in my YML

``` yml
fr:
  onelevel:
    secondlevel:
      thirdlevel:
        something: "En français !"
```

Calling from rails `t(:onelevel)` will actually show the whole hash of translations

``` yml
{:onelevel=>{:secondlevel=>{:thirdlevel=>{:something=>"En français!"}}}}
```

Hopefully, it doesn't work with `t(:en)`, but it can potentially become a security issue (leaking translation data)
