### ISSUE TITLE
Error message interpolation should be done inside the messages themselves

### ISSUE THREAD

**Issue by johnnyshields** [svenfuchs/rails-i18n#532]
Currently the attribute name in error messages is setup as follows:

```
  errors:
    format: "%{attribute} %{message}"
    messages:
      accepted: must be accepted
      blank: can't be blank
      present: must be blank
```

Any reason why we don't get rid of the "format" node and instead do:

```
  errors:
    messages:
      accepted: "%{attribute} must be accepted"
      blank: "%{attribute} can't be blank"
      present: "%{attribute} must be blank"
```

This would be much more flexible as it's not necessarily natural in all locales to force ALL error messages to have the same sentence structure. (In addition, there are some error messages where you may not want to use the attribute name at all.)
