### ISSUE TITLE
Translation is failing with upcase flag

### ISSUE THREAD

**Issue by bmsatierf** [svenfuchs/rails-i18n#564]
According to the [standard lib](http://ruby-doc.org/core-2.2.0/Time.html), the flag `^` should upcase the result string, so considering the following setup:

``` yml
pt-BR:
  date:
    formats:
      default: "%B %d, %Y"
    month_names: [~, Janeiro, Fevereiro, Março, Abril, Maio, Junho, Julho, Agosto, Setembro, Outubro, Novembro, Dezembro]
```

The statement `I18n.l '6/7/2015'.to_date` results in `Julho 06, 2015`, which is OK.

Now, considering the following setup:

``` yml
pt-BR:
  date:
    formats:
      default: "%^B %d, %Y"
    month_names: [~, Janeiro, Fevereiro, Março, Abril, Maio, Junho, Julho, Agosto, Setembro, Outubro, Novembro, Dezembro]
```

The statement `I18n.l '6/7/2015'.to_date` results in `JULY 06, 2015`.

Note that the flag `^` was properly applied (upcase), but the translation failed, as it should be `JULHO`.

Am I missing something?
