### ISSUE TITLE
missing interpolation argument :attribute

### ISSUE THREAD

**Issue by TravisTam** [svenfuchs/rails-i18n#609]
I have set my locale to zh-HK and seems that is difference from using zh-TW. It shows below errors. Can many one advise how can I fix it?
```
missing interpolation argument :attribute in "%{attribute}驗證失敗︰%{errors}" ({:errors=>"Nickname是無效的"} given)
```

**Comment by TravisTam** [comment]
in the locale file, it is found %{attribute} is no longer existed in both 'en.yml' and 'zh-TW.yml'. I would like to know Is there any special setup I need to do to satisfy the zh-HK locale setting?
```
zh-HK:
   errors:
      messages:
         record_invalid: "%{attribute}驗證失敗︰%{errors}"
```

```
zh-TW:
   errors:
      messages:
         record_invalid:'校驗失敗: %{errors}'
```
```
en:
   errors:
      messages:
         record_invalid:'  'Validation failed: %{errors}'
```
