### ISSUE TITLE
how to config a model under a namespace

### ISSUE THREAD

**Issue by foolishchow** [svenfuchs/rails-i18n#680]
I have a model below,but I don't how to config in my locales 
```ruby
class System::Menu < ApplicationRecord

end
````

should I config like this ?

```yml
zh-CN:
  activerecord:
    models:
      system:
        menu: SystemMenu
    attributes:
      system::menu:
        label: MenuName
```

**Comment by javierguajardo** [comment]
@foolishchow I would have to take look at your Rails app version number to give you a clear answer, but I found a Stack Overflow link that might help.

https://stackoverflow.com/questions/7693040/how-to-translate-model-in-ruby-class-module-namespace

Your config would have to look like this:

```
zh-CN:
  activerecord:
    models:
      system/menu: SystemMenu
    attributes:
      system/menu:
        label: MenuName
```
