### ISSUE TITLE
Cascade search of a relative key

### ISSUE THREAD

**Issue by rtrv** [svenfuchs/rails-i18n#720]
Hello. I'm trying to make `t(key)` calls DRY with not using `scope` or full path to a key.
I use calls like `t('.example')`. It's being resolved as something like `t('en.namespace.controller_name.action_name.view_name.example')`.

If I render some partials which both use this key, I have to either use scope, or write to localization file duplicating key:
```
first_view_name:
  example: Example value
second_view_name:
  example: Example value
```

Is there any way to DRY it and still use relative keys? I mean, if `t('en.namespace.controller_name.action_name.view_name.example')` doesn't exist, look for `t('en.namespace.controller_name.action_name.example')`, ... and `t('en.example')`.
If it's not possible now, would you accept a contribution with such functionality, enabling by extra configuration key?
