### ISSUE TITLE
0.1 rounded as 1 by french translation

### ISSUE THREAD

**Issue by Dorian** [svenfuchs/rails-i18n#731]
From: https://github.com/rails/rails/issues/29727

### Steps to reproduce

`config/locales/en.yml`:

```yaml
fr:
  points:
    zero: "0 point"
    one: "1 point"
    other: "%{count} points"
```

`config/locales/fr.yml`:

```yaml
fr:
  points:
    zero: "0 point"
    one: "1 point"
    other: "%{count} points"
```

### Expected behavior

```ruby
>> I18n.locale = :en; I18n.t(:points, count: 0.1)
=> "0.1 points"
>> I18n.locale = :fr; I18n.t(:points, count: 0.1)
=> "0.1 points"
```

### Actual behavior

```ruby
>> I18n.locale = :en; I18n.t(:points, count: 0.1)
=> "0.1 points"
>> I18n.locale = :fr; I18n.t(:points, count: 0.1)
=> "1 point"
```

### System configuration
**Rails version**: `5.1.1`
**Ruby version**: `2.4.1`

**Comment by Dorian** [comment]
So, it's a bug on my side, e.g.

```yaml
fr:
  points:
    zero: "0 point"
    one: "%{count} point"
    other: "%{count} points"
```

Because `:one` can be reached for `1.1` and `0.4` for instance in french

source: https://github.com/svenfuchs/rails-i18n/blob/master/lib/rails_i18n/common_pluralizations/one_upto_two_other.rb

specs: https://github.com/svenfuchs/rails-i18n/blob/master/spec/unit/pluralization/one_upto_two_other.rb

Thanks for this great gem
