### ISSUE TITLE
proyect es-PE.yml overriden keys  don't override base es-PE.yml from the gem

### ISSUE THREAD

**Issue by silva96** [svenfuchs/rails-i18n#821]
Currently we have this configuration:

Gem version: rails-i18n (5.1.2)
Rails Version: rails (5.0.2)

```
    config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}')]
    config.i18n.default_locale = :'es-CL'
    config.i18n.available_locales = [:'es-CL', :'es-PE', :'en-CL', :'en-PE', :'en', :'es']
    config.i18n.fallbacks = {:'es-PE' => :'es-CL', :'es' => :'es-CL', :'en-PE' => :'en-CL', :'en' => :'en-CL'}
```

And this locale file for Perú

```
es-PE:
  number:
    currency:
      format:
        delimiter: '.'
        format: '%u %n'
        precision: 2
        separator: ','
        strip_insignificant_zeros: true
        significant: false
        unit: 'S/'
  other_project_key: it works
```

calling `I18n.t("number.currency.format", locale: :'es-PE')`
returns
```
{:delimiter=>",", :format=>"%u%n", :precision=>2, :separator=>".", :strip_insignificant_zeros=>false, :significant=>false, :unit=>"S/."}
```

Which is not correct from the yml file that overrrides the values.
