### ISSUE TITLE
Wrong display of the number of Russian language

### ISSUE THREAD

**Issue by afuno** [svenfuchs/rails-i18n#855]
```yaml
ru:
  general:
    pluralization:
      subtopic:
        one: 1 подтема (1)
        few: "%{count} подтемы (2)"
        many: "%{count} подтем (3)"
        other: "%{count} подтем (4)"
```

```slim
. = t('general.pluralization.subtopic', count: '21')
. = t('general.pluralization.subtopic', count: '22')
. = t('general.pluralization.subtopic', count: 21)
```

Output:

```
21 подтем (4)    # ok - it is a string
22 подтем (4)    # ok - it is a string
1 подтема (1)    # not ok
```
