### ISSUE TITLE
Danish locale has a key inconsistency with English

### ISSUE THREAD

**Issue by davideluque** [svenfuchs/rails-i18n#860]
rails/locale/en.yml 
```yaml
en:
  errors:
    messages:
      too_short:
        one: is too short (minimum is 1 character)
        other: is too short (minimum is %{count} characters)
```

rails/locale/da.yml 
```yaml
da:
  errors:
    messages:
      too_short: er for kort (mindst %{count} tegn)
```
