### ISSUE TITLE
How to split distance_in_words for minutes?

### ISSUE THREAD

**Issue by afuno** [svenfuchs/rails-i18n#904]
For hours, months and years there are the [following][1] translations:

```yaml
about_x_hours:
  one:   "about 1 hour"
  other: "about %{count} hours"
about_x_months:
  one:   "about 1 month"
  other: "about %{count} months"
about_x_years:
  one:   "about 1 year"
  other: "about %{count} years"

x_months:
  one:   "1 month"
  other: "%{count} months"
x_months:
  one: in 1 month
  other: "in %{count} months"
x_years:
  one: in 1 year
  other: "in %{count} years"
```

But for `x_minutes` and `x_days` there is no `about_x_minutes` and `about_x_days`.

Please tell me how can I add these options for translations?

  [1]: https://github.com/rails/rails/blob/master/actionview/lib/action_view/locale/en.yml
