### ISSUE TITLE
feature: inflections in translations (specific distance_of_time...)

### ISSUE THREAD

**Issue by fwolfst** [svenfuchs/rails-i18n#908]
Hi
Probably related to https://github.com/svenfuchs/rails-i18n/issues/885 , in German you'd apply different cases for
```
Age: 3 hours
Alter: 3 Stunde
```
and
```
Created 3 hours ago
Vor 3 StundeN angelegt
```
The capitalized `N` is for illustrative purposes only.

`distance_of_time_in_words` and the related functions accept a translation-scope. If the `rails-i18n` gem would support 'cased' (inflected) translations and a convention for it, I could PR the German translations.

One candidate could be:
```yml
datetime:
    distance_in_words: # 'original'
      about_x_hours:
        one: etwa eine Stunde
        other: etwa %{count} Stunden
      inflected:
        dativ: # German case name
          about_x_hours:
            one: etwa einer Stunde # eineR
            other: etwa %{count} Stunden
```

or, more general, a `variant` scope with custom additions (apparently in hungarian you might want a `past` and `future` variant).
